sudo: required
dist: trusty
language: cpp
matrix:
  include:
    - compiler: gcc
      env: NO_STATIC_ASSERTS=true
    - compiler: clang
      env: NO_STATIC_ASSERTS=true
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gdb

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - BOOST_VERSION=1.60.0
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  - if [[ "${BOOST_VERSION}" == "default" ]]; then BOOST_VERSION=1.60.0; fi

  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - echo "using : ${CC} :  : ${CXX} ;" > ~/user-config.jam
  - cat ~/user-config.jam

  - if [[ "${BOOST_VERSION}" == "1.60.0" ]]; then BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz"; fi
  - if [[ "${BOOST_URL}" != "" ]]; then mkdir boost && travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C boost; fi

  - cd boost/tools/build && ./bootstrap.sh && ./b2 install --prefix=${DEPS_DIR}/b2
  - export PATH=${DEPS_DIR}/b2/bin:${PATH}

  - export BOOST_ROOT=${DEPS_DIR}/boost

  - cd ${TRAVIS_BUILD_DIR}
  - pwd
  - ls

script:
  - $CC --version
  - $CXX --version

  - cd test

  - if [[ ${NO_STATIC_ASSERTS} != "" ]]; then export FLAGS="--toolset=${CC} --no-static-asserts"; else export FLAGS="--toolset=${CC}"; fi

  - b2 clean
  - rm -rf stage
  - ./run_tests.sh ${FLAGS} --without-eris
  - ./lua_internal_tests.sh

  - b2 clean
  - rm -rf stage
  - ./run_tests.sh ${FLAGS} --without-eris --with-lua-32bit

  - b2 clean
  - rm -rf stage
  - ./run_tests.sh ${FLAGS}
#  - ./lua_internal_tests.sh

  - b2 clean
  - rm -rf stage
  - ./run_tests.sh ${FLAGS} --with-lua-32bit
#  - ./lua_internal_tests.sh
